# Generated by Django 2.1.4 on 2019-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
    ]
