# Generated by Django 2.1.9 on 2019-07-26 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190626_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.TextField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
