# Generated by Django 2.1.9 on 2019-07-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
